### ISSUE TITLE
Betas values in results always be zero

### ISSUE THREAD

**Issue by leonzhong** [bharat-b7/MPI_MeshRegistration#8]
Hi, Thank you for the amazing work! I am trying to fit smpl-h to the scanned model,  the 'pose' and 'trans' values in the smpl result seems correct, but the 'betas'(i.e. the shapes) values are always zero.  Can any one please help with this? 
I run the python script using the sample 3d models with smplh and smplhd，neither of them got the proper shape results.

`python3 smpl_registration/fit_SMPLHD.py data/mesh_1/scan.obj data/mesh_1/3D_pose.json data/mesh_1/ -gender male -hands`

**Comment by yifeiyin04** [comment]
Hi, I have met the same problem and solved it by changing this line  _https://github.com/bharat-b7/MPI_MeshRegistration/blob/23547f610ad6ec64cde638cf4b888488a00fdb7d/lib/smpl/smplpytorch/smplpytorch/pytorch/smpl_layer.py#L104_ to `if th_betas is None`.

**Comment by leonzhong** [comment]
> Hi, I have met the same problem and solved it by changing this line
> 
> https://github.com/bharat-b7/MPI_MeshRegistration/blob/23547f610ad6ec64cde638cf4b888488a00fdb7d/lib/smpl/smplpytorch/smplpytorch/pytorch/smpl_layer.py#L104
> 
> _ _ to `if th_betas is None`.

Thank you so much ! Problem is solved.
